### ISSUE TITLE
Stinger Reload Bug

### ISSUE THREAD

**Issue by ThunderRazor** [ArcanePariah/Night-of-the-Dead#182] opened 2018-02-24 19:22 UTC
Manual reloads bug the attack ability using stinger if the player performs any actions while reloading. This seems to have happened since the latest SC2 patches.

**Comment by dave-sWpR46Ae** [comment] 2018-02-25 22:03
Caused by https://github.com/ArcanePariah/Night-of-the-Dead/commit/418820f6434dfdbc94d608733c4118ac3d1e259a

**Comment by NiktosNOTD** [comment] 2018-03-01 15:23
Rockz commit changes way less that it seems at first, all 'trash' in mapscript.galaxy gets discarded, when it is recompiled on save with changes to 'Triggers' file. 
So this commit did 2 persistent changes
-1 intended autoban related it's 28xx lines of triggers file code
-1 unintented with adding the wait it's everything in 38xxx lines chunk

IMO just someone submitting a hotfix which will remove the wait from 'AmmoUsage' trigger
![](https://cdn.discordapp.com/attachments/405164939528110100/416958714596294679/sting_issue.png)
Will be less hassle for Arcane than reverting the previous merge.

**Comment by dave-sWpR46Ae** [comment] 2018-03-01 18:11
Somewhere along the line we lost nova's smaller click circle size as well, and I'm willing to bet it was my patch that did it (no triggers involved in that patch).

**Comment by ThunderRazor** [comment] 2018-03-02 21:59
I will experiment a bit with optimising this ammo usage trigger. In the meantime, if anyone comes up with a solution better than what I end up with then kudos. Thanks Nik!

**Comment by dave-sWpR46Ae** [comment] 2018-03-04 12:01
#188 removes the line.

#187 removes the line and fixes another stinger issue (stinger taking ammo without firing).

**Comment by dave-sWpR46Ae** [comment] 2018-03-14 21:31
Looks good, I think you can close this now.

**Closed as completed** 2018-04-16 04:14 UTC
